[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  '@lib=./lib',
  '@openzeppelin/contracts=./lib/openzeppelin-contracts/contracts',
  '@diamond-3-hardhat=lib/diamond-3-hardhat/contracts',
  '@solady/=lib/solady/src/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
